const projectsDetail = [{
  LinkToSource: 'https://github.com/souad988/youtube',
  linkToLiveVersion: 'https://souad988.github.io/youtube/',
  image: './media/images/projects/youtube.png',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the relea',
  name: 'youtube',
  technologies: ['Html', 'css'],
},
{
  LinkToSource: 'https://github.com/souad988/portfolio',
  linkToLiveVersion: 'https://souad988.github.io/portfolio/',
  image: './media/images/projects/portfolio.png',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the relea',
  name: 'portfolio',
  technologies: ['Html', 'css', 'javascript'],
},
{
  LinkToSource: 'https://github.com/souad988/e-com',
  linkToLiveVersion: 'https://souad988.github.io/e-com/',
  image: './media/images/projects/youtube.png',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the relea',
  name: 'ecom',
  technologies: ['Html', 'css', 'js', 'python', 'django'],
},
{
  LinkToSource: 'https://github.com/souad988/youtube',
  linkToLiveVersion: 'https://souad988.github.io/youtube/',
  image: './media/images/projects/youtube.PNG',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the relea',
  name: 'youtube1',
  technologies: ['Html', 'css'],
},
{
  LinkToSource: 'https://github.com/souad988/portfolio',
  linkToLiveVersion: 'https://souad988.github.io/portfolio/',
  image: './media/images/projects/portfolio.png',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the relea',
  name: 'portfolio1',
  technologies: ['Html', 'css', 'javascript'],
},
{
  LinkToSource: 'https://github.com/souad988/e-com',
  linkToLiveVersion: 'https://souad988.github.io/e-com/',
  image: './media/images/projects/youtube.png',
  description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the relea',
  name: 'ecom1',
  technologies: ['Html', 'css', 'js', 'python', 'django'],
}];